// fixtures/extraction/vue/cross_file/source.vue
<script setup>
// Phase 4a fixture: cross-file `script setup` import. `foo` is defined in
// './other'. The vue extractor must emit a StructuredPendingRelationship
// with target.terminal_name="foo" and target.import_context="./other".
// The intra-file local_helper() resolves concretely.

import { foo } from './other';

function local_helper() {
    return 42;
}

function entry() {
    foo();
    return local_helper();
}
</script>

<template>
    <div>{{ entry() }}</div>
</template>

// fixtures/extraction/tsx/cross_file/source.tsx
// Phase 4a fixture: cross-file class import with JSX. Foo is defined in
// another file at './other'. The tsx extractor (TypeScriptExtractor) must
// emit a StructuredPendingRelationship with target.terminal_name="Foo" and
// target.import_context="./other". The intra-file local_helper() resolves.

import { Foo } from './other';

function local_helper(): number {
    return 42;
}

export function entry() {
    const x = new Foo();
    return <Foo>{local_helper()}</Foo>;
}
