// fixtures/extraction/tsx/test_roles/source.tsx
describe("tsx roles", () => {
  beforeEach(() => {});
  test("renders a TSX test case", () => {
    const view = <output>ready</output>;
    return view;
  });
});

function testNamedButOrdinary(): JSX.Element {
  return <span>ordinary</span>;
}

const ordinary = {
  test(_name: string, callback: () => JSX.Element): JSX.Element {
    return callback();
  },
};

ordinary.test("ordinary member call", () => <span>not a test</span>);

// fixtures/extraction/vue/test_roles/source.vue
<template>
  <output>ready</output>
</template>

<script setup lang="ts">
describe("vue embedded roles", () => {
  beforeEach(() => {});
  test("renders a Vue test case", () => {});
});

function testNamedButOrdinary(): void {}

const ordinary = {
  test(_name: string, callback: () => void): void {
    callback();
  },
};

ordinary.test("ordinary member call", () => {});
</script>
